test ci-cd
test ci-cd

diff --git a/.github/workflows/main_deploy.yml b/.github/workflows/main_deploy.yml
--- a/.github/workflows/main_deploy.yml
+++ b/.github/workflows/main_deploy.yml
@@ -43,10 +43,11 @@ jobs:
         run: npm install -g sfdx-git-delta@3.3.0
         shell: bash
 
-      - name: Verify sfdx-git-delta installation
+      - name: 'Verify sfdx-git-delta installation'
         run: |
-            which sfdx-git-delta
-            sfdx-git-delta --version
+          echo "Checking sfdx-git-delta installation..."
+          which sfdx-git-delta || echo "sfdx-git-delta not found!"
+          sfdx-git-delta --version || echo "sfdx-git-delta execution failed!"
         shell: bash
 
       - name: 'Generate metadata delta pull request'
